image:
  - Windows
  - macOS

platform:
  - x64

for:
-
  matrix:
    only:
      - image: Windows
  build_cloud: GILVANDENDREA21
  cache:
    - node_modules
    - '%USERPROFILE%\.electron'
    - "%LOCALAPPDATA%\\Yarn"
  init:
    - git config --global core.autocrlf input
  install:
    - ps: Install-Product node 14 x64
    - yarn
  build_script:
    - yarn dist-win
-
  matrix:
    only:
      - image: macOS
  cache:
    - node_modules
    - '~\.electron'
  install:
    - npm install -g yarn
    - yarn
  build_script:
    - yarn dist-mac

test: off

build: off

artifacts:
  - path: dist/*.exe
    name: Exe
  - path: dist/*.dmg
    name: Dmg
  - path: dist/*.intunemac
    name: intunemac
  - path: dist/*.intunewin
    name: Intunewin

