environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Windows
      APPVEYOR_BUILD_WORKER_CLOUD: GILVANDENDREA21
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS

platform:
  - x64

for:
-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: Windows
  cache:
    - node_modules
    - '%USERPROFILE%\.electron'
    - "%LOCALAPPDATA%\\Yarn"
  init:
    - git config --global user.name "vddgil"
    - echo %GH_TOKEN%
    - git config --global user.password "%GH_TOKEN%"
  install:
    - yarn
  build_script:
    - yarn dist-win
-
  matrix:
    only:
      - APPVEYOR_BUILD_WORKER_IMAGE: macOS
  cache:
    - node_modules
    - '~\.electron'
  install:
    - npm install -g yarn
    - yarn
  build_script:
    - yarn dist-mac

test: off

build: off

artifacts:
  - path: dist/*.exe
    name: Exe
  - path: dist/*.dmg
    name: Dmg
  - path: dist/*.intunemac
    name: intunemac
  - path: dist/*.intunewin
    name: Intunewin

