image:
  - Visual Studio 2019
  - macOS-BigSur

platform:
  - x64

skip_non_tags: true

for:
-
  matrix:
    only:
      - image: macOS-BigSur
  cache:
    - node_modules
    - '~\.electron'
  install:
    - nvm install 14.18.2
    - nvm use 14.18.2
    - npm install -g yarn
    - sudo xcode-select -r
    - yarn
  build_script:
    - yarn dist-mac
-
  matrix:
    only:
      - image: Visual Studio 2019
  cache:
    - node_modules
    - "%USERPROFILE%\\.electron"
    - "%LOCALAPPDATA%\\Yarn"
  init:
    - git config --global core.autocrlf input
  install:
    - ps: Install-Product node 14 x64
    - ps: Start-FileDownload 'https://scribe-desktop-app.s3.eu-west-3.amazonaws.com/CodeSignTool-v1.2.2-windows.zip'
    - tar -xf CodeSignTool-v1.2.2-windows.zip
    - yarn
  build_script:
    - yarn dist-win

test: off

build: off

artifacts:
  - path: dist/*.exe
    name: Exe
  - path: dist/*.dmg
    name: Dmg

notifications:
  - provider: Slack
    incoming_webhook:
      secure: YNo9GMVLtLRa0VS1ijvomJnRbzsgaMHBe8fbEssHEAtLodfBm1PffB2WBqFhux0JG2tuU02XswC9QFE+7iJhW63VJLr5obyi/Yjd0f7Wz7kTUKOocR8JzsGuXItm2Uw8
    channel: '#app-veyor'
