image:
  - Visual Studio 2019
  - macOS

platform:
  - x64

for:
-
  matrix:
    only:
      - image: Visual Studio 2019
  cache:
    - node_modules
    - '%USERPROFILE%\.electron'
  init:
    - git config --global core.autocrlf input
  install:
    - ps: Install-Product node 12 x64
    - yarn
  build_script:
    - yarn dist-win
-
  matrix:
    only:
      - image: macOS
  cache:
    - node_modules
    - '~\.electron'
  build_script:
    - yarn dist-mac

test: off

build: off

artifacts:
  - path: dist/*.dmg
    name: Dmg
  - path: dist/*.pkg
    name: Pkg
  - path: dist/*.zip
    name: Zip

