build_cloud: GILVANDENDREA21
image: Windows

platform:
  - x64

cache:
  - node_modules
  - '%USERPROFILE%\.electron'
  - "%LOCALAPPDATA%\\Yarn"
init:
  - git config --global credential.helper store
  - git config --global core.autocrlf input
  - ps: Set-Content -Path "$HOME\.git-credentials" -Value "https://$($env:GH_TOKEN):x-oauth-basic@github.com`n" -NoNewline
install:
  - ps: Install-Product node 14 x64
  - yarn
build_script:
  - yarn dist-win

test: off

build: off

artifacts:
  - path: dist/*.exe
    name: Exe
  - path: dist/*.dmg
    name: Dmg
  - path: dist/*.intunemac
    name: intunemac
  - path: dist/*.intunewin
    name: Intunewin

