image:
  - Visual Studio 2019
  - macOS

platform:
  - x64

for:
-
  matrix:
    only:
      - image: Visual Studio 2019
  cache:
    - node_modules
    - "%USERPROFILE%\\.electron"
    - "%LOCALAPPDATA%\\Yarn"
  init:
    - git config --global core.autocrlf input
    - curl -o %LOCALAPPDATA%\\CodeSignTool.zip https://scribe-desktop-app.s3.eu-west-3.amazonaws.com/CodeSignTool-v1.2.0-windows.zip
    - tar -xf %LOCALAPPDATA%\\CodeSignTool.zip
  install:
    - ps: Install-Product node 14 x64
    - yarn
  build_script:
    - yarn dist-win
-
  matrix:
    only:
      - image: macOS
  cache:
    - node_modules
    - '~\.electron'
  install:
    - npm install -g yarn
    - yarn
  build_script:
    - yarn dist-mac

test: off

build: off

artifacts:
  - path: dist/*.exe
    name: Exe
  - path: dist/*.dmg
    name: Dmg
  - path: dist/*.pkg
    name: Pkg
  - path: dist/*.zip
    name: Zip
  - path: dist/*.intunemac
    name: intunemac
  - path: dist/*.intunewin
    name: Intunewin

notifications:
  - provider: Slack
    incoming_webhook:
      secure: YNo9GMVLtLRa0VS1ijvomJnRbzsgaMHBe8fbEssHEAtLodfBm1PffB2WBqFhux0JG2tuU02XswC9QFE+7iJhW63VJLr5obyi/Yjd0f7Wz7kTUKOocR8JzsGuXItm2Uw8
    channel: '#app-veyor'
