version: 2.1
jobs:
  build:
    working_directory: ~/repo
    macos:
      xcode: "11.4"
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: yarn && yarn dist-mac
      - store_artifacts:
          path: dist
          destination: dist
